baseURL: "/"
languageCode: "en-us"
title: "Aaron Bresser"
theme: hugo-profile

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    title: "Aaron Bresser"
    subtitle: "Desarrollador de Aplicaciones Web"
    content: "Utilizo tecnologías modernas para construir sitios web que se vean bien y sean óptimos y funcionen correctamente"
    image: /images/hero.svg
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://example.com
        - icon: fab fa-twitter
          url: https://example.com
      customIcons:
        - icon: /fav.png
          url: "https://example.com"

  # About
  about:
    enable: true
    title: "Sobre mí"
    image: "/images/yo.png"
    content: |-
      Programador con 1 año de experiencia. Me caracterizo por generar códigos para empresas de diferentes sectores. 
      Uno de mis proyectos más importantes fue la creación del sitio web de la Revista Actualidad, esta recibe 250.000 visitas semanales.
    skills:
      enable: true
      title: "Aquí dejo los lenguajes que utilizo:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "MySQL"
        - "Python"
        - "C++"

  # Experience
  experience:
    enable: true
    title: "Experiencia"
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "Ver el proyecto"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    title: "Educación"
    # index: true
    items:
      - title: "Técnico Superior en Desarrollo de Aplicaciones Web"
        school:
          name: "CPIFP Los Enlaces"
          url: "https://example.org"
        date: "2021 - 2022"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique

  # projects
  projects:
    enable: true
    title: "Mis proyectos"
    items:
      - title: Acme
        content: Creación de una página
        featured:
          name: Enlace al repositorio
          link: https://github.com/AaronBresser/acme.git
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"

      - title: Portfolio
        content: Un portfolio personal para las empresas
        featured:
          name: Enlace al repositorio
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        link: https://github.com/AaronBresser/AaronBresser.github.io.git

  #Contact
  contact:
    enable: true
    title: "Contáctame"
    content: Os dejo mi correo a vuestra disposición para cualquier cosa.
    email: gurusabarisha@gmail.com
    btnName: Correo

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com